# API S3 Bucket Creation
service: api-${file(config.json):BUCKET}
plugins:
  - serverless-dotenv-plugin
provider:
  environment:
  # Runtime
  name: aws
  runtime: nodejs16.x

  # Stage DEV/PROD
  stage: ${file(config.json):STAGE}

  # Region Paris
  region: eu-west-3 

  # API IAM Roles allow PutObject
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${file(config.json):BUCKET}/*"

# Define NodeJS function to run
functions:

  # We define a function called "store"
  store:
    # Where function with name "handle" will run
    handler: api.handle

    # Configure POST event
    events:
      - http:
          path: /
          method: post
          cors: false

# Configure Frontend S3 Bucket
resources:
  Resources:

    # Frontend S3 Bucket Creation
    FrontendS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s2-isarria-dev
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        WebsiteConfiguration:
          IndexDocument: index.html

    # Frontend S3 Bucket Policy
    FrontendS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${file(config.json):BUCKET}
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::${file(config.json):BUCKET}/*
              Principal: "*"
